_itemsSource["unique"] = {
	{
		name = "atk_chain",
		label = "ATK Chain",
		description = "Aim To Kill",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "atk",
	},
	{
		name = "vagos_chain",
		label = "Vagos Chain",
		description = "Vagos",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "vagos",
	},
	{
		name = "dorky_chain",
		label = "Dorky Chain",
		description = "Dorky",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dorky",
	},
	{
		name = "ballas_chain",
		label = "Ballas Chain",
		description = "Balling on the Ballas",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ballas",
	},
	{
		name = "WhiteStar_Mask",
		label = "WhiteStar Mask",
		description = "⛥",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "WS",
	},
	{
		name = "ssf_chain",
		label = "SSF Chain",
		description = "South Side Families",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssf",
	},
	{
		name = "mint_mate_chain",
		label = "Mint Mate Chain",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate",
		iconOverride = "rlg_chain",
	},
	{
		name = "snow_chain",
		label = "Snowboys Chain",
		description = "❄️",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "snow",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_2",
		label = "Mint Mate Chain (Large)",
		description = "It's Mint Mate ... but large",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate2",
		iconOverride = "rlg_chain",
	},
}
