table.insert(_defaultJobData, {
	Type = "Government",
	LastUpdated = 1682170258,
	Id = "police",
	Name = "Police",
	Salary = 1100,
	SalaryTier = 1,
	Workplaces = {
		{
            Id = 'sapr',
            Name = 'San Andreas Park Rangers',
            Grades = {
                {
                    Id = 'warden',
                    Name = 'Game Warden',
                    Level = 99,
                    Salary = 5000,
                    Permissions = {
                        PD_HIGH_COMMAND = true,
                    },
                },
                {
                    Id = 'dwarden',
                    Name = 'Assistant Game Warden',
                    Level = 90,
                    Salary = 4500,
                    Permissions = {
                        PD_HIGH_COMMAND = true,
                    },
                },
                {
                    Id = 'awarden',
                    Name = 'Deputy Game Warden',
                    Level = 80,
                    Salary = 4000,
                    Permissions = {
                        PD_HIGH_COMMAND = true,
                    },
                },
                {
                    Id = 'major',
                    Name = 'Major',
                    Level = 75,
                    Salary = 3750,
                    Permissions = {
                        PD_HIGH_COMMAND = true,
                        },
                },
                {
                    Id = 'captain',
                    Name = 'Captain',
                    Level = 70,
                    Salary = 3500,
                    Permissions = {
                        PD_COMMAND = true,
                        },
                },
                {
                    Id = 'lieutenant',
                    Name = 'Lieutenant',
                    Level = 60,
                    Salary = 3000,
                    Permissions = {
                        PD_COMMAND = true,
                    },
                },
                {
                    Id = 'sergeant',
                    Name = 'Sergeant',
                    Level = 50,
                    Salary = 2500,
                    Permissions = {
                        PD_SUPERVISOR = true,
                    },
                },
                {
                    Id = 'mranger',
                    Name = 'Ranger 1st Class',
                    Level = 20,
                    Salary = 2000,
                    Permissions = {
                        PD_SUPERVISOR = true,
                    },
                },
                {
                    Id = 'sranger',
                    Name = 'Senior Ranger',
                    Level = 15,
                    Salary = 1250,
                    Permissions = {
                    },
                },
                {
                    Id = 'ranger',
                    Name = 'Ranger',
                    Level = 10,
                    Salary = 950,
                    Permissions = {
                    },
                },
                {
                    Id = 'pranger',
                    Name = 'Probationary Ranger',
                    Level = 2,
                    Salary = 500,
                    Permissions = {
                    },
                },
                {
                    Id = 'cadet',
                    Name = 'Cadet',
                    Level = 1,
                    Salary = 250,
                    Permissions = {
                    },
                },
            }
        },
		{
			Id = "lspd",
			Name = "Los Santos Police Department",
			Grades = {
				{
					Id = "chief",
					Name = "Chief",
					Level = 99,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "achief",
					Name = "Assistant Chief",
					Level = 90,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "sofficer",
					Name = "Senior Officer",
					Level = 15,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "officer",
					Name = "Officer",
					Level = 10,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "pofficer",
					Name = "Probationary Officer",
					Level = 2,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
					},
				},
			},
		},
		{
			Id = "lscso",
			Name = "Los Santos Sheriff\'s Office",
			Grades = {
				{
					Id = "sheriff",
					Name = "Sheriff",
					Level = 99,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "usheriff",
					Name = "Undersheriff",
					Level = 90,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "sdeputy",
					Name = "Senior Deputy",
					Level = 15,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "deputy",
					Name = "Deputy",
					Level = 10,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "pdeputy",
					Name = "Probationary Deputy",
					Level = 2,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
					},
				},
			},
		},
		{
			Id = "sast",
			Name = "San Andreas State Troopers",
			Grades = {
				{
					Id = "colonel",
					Name = "Colonel",
					Level = 99,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "major",
					Name = "Major",
					Level = 90,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_MANAGE = true,
						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_WITHDRAW = true,
						BANK_ACCOUNT_TRANSACTIONS = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "captain",
					Name = "Captain",
					Level = 70,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						FLEET_VEHICLES_4 = true,
						FLEET_MANAGEMENT = true,
						PD_HIGH_COMMAND = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "lieutenant",
					Name = "Lieutenant",
					Level = 60,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						FLEET_VEHICLES_3 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,

						BANK_ACCOUNT_DEPOSIT = true,
						BANK_ACCOUNT_BALANCE = true,
					},
				},
				{
					Id = "sergeant",
					Name = "Sergeant",
					Level = 50,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						FLEET_VEHICLES_2 = true,
						PD_COMMAND = true,
						MDT_HIRE = true,
						MDT_FIRE = true,
						MDT_PROMOTE = true,
						MDT_EDIT_EMPLOYEE = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_DISCIPLINARY_REPORTS = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "corporal",
					Name = "Corporal",
					Level = 20,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "strooper",
					Name = "Senior Trooper",
					Level = 15,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						FLEET_VEHICLES_1 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						MDT_POLICE_FTO_REPORTS = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "trooper",
					Name = "Trooper",
					Level = 10,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "ptrooper",
					Name = "Probationary Trooper",
					Level = 2,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
						impound_police = true,
					},
				},
				{
					Id = "cadet",
					Name = "Cadet",
					Level = 1,
					Permissions = {
						ems_alerts = true,
						police_alerts = true,
						FLEET_VEHICLES_0 = true,
						MDT_INCIDENT_REPORT_VIEW = true,
						MDT_INCIDENT_REPORT_CREATE = true,
						MDT_CIVILIAN_REPORT_VIEW = true,
						MDT_CIVILIAN_REPORT_CREATE = true,
						JOB_STORAGE = true,
						impound = true,
                    },
                },
            }
        },
    }
})
